// Entity dependency lookup. PLATFORM-CONCEPTS §2.
//
// Generated by `npm run deps` from the 111 packages. This module only reads it.
//
// The sentence this exists to enable: not "this SoC reading is 14 minutes old"
// but "and it feeds the battery-to-6am estimate, the reserve guard and two
// automations". The first is a fact; the second tells you whether to care.

import raw from "./generated/dependencies.json";

export type DepKind = "automation" | "script" | "scene" | "template" | "config";
export type Dep = { file: string; kind: DepKind };

const index = (raw as { index: Record<string, Dep[]> }).index;

export const depsGeneratedAt = (raw as { generatedAt: string }).generatedAt;
export const depsEntityCount = (raw as { entityCount: number }).entityCount;

/** Everything that references this entity. Empty array if nothing does. */
export function dependents(entityId: string): Dep[] {
  return index[entityId] ?? [];
}

export function dependentCount(entityId: string): number {
  return (index[entityId] ?? []).length;
}

/**
 * The phrase to put next to a stale or dead reading.
 *
 * Returns "" when nothing depends on it — an entity with no readers is exactly
 * the case where staleness does NOT matter, and saying "0 things depend on this"
 * would give it the same visual weight as one that breaks the alarm.
 */
export function dependsPhrase(entityId: string): string {
  const n = dependentCount(entityId);
  if (n === 0) return "";
  return n === 1 ? "1 thing depends on this" : `${n} things depend on this`;
}

/** Grouped for the dependency sheet: readers by kind, most consequential first. */
export function groupedDependents(entityId: string): { kind: DepKind; files: string[] }[] {
  const order: DepKind[] = ["automation", "script", "template", "scene", "config"];
  const by = new Map<DepKind, string[]>();
  for (const d of dependents(entityId)) {
    const list = by.get(d.kind) ?? [];
    if (!list.includes(d.file)) list.push(d.file);
    by.set(d.kind, list);
  }
  return order.filter((k) => by.has(k)).map((k) => ({ kind: k, files: by.get(k)!.sort() }));
}

/** The busiest entities — used by Diagnostics to say what a subsystem feeds. */
export function busiest(prefixes: string[], limit = 5): { id: string; n: number }[] {
  return Object.keys(index)
    .filter((id) => prefixes.some((p) => id.includes(p)))
    .map((id) => ({ id, n: index[id].length }))
    .sort((a, b) => b.n - a.n)
    .slice(0, limit);
}
