import type { HassEntities } from "./ha";

// Realistic offline dataset (values from DASHBOARD_DATA_SNAPSHOT.md, with a
// few tweaked to daytime so charts/flow look alive). Enabled with ?mock=1 —
// lets the UI run with no Home Assistant connection, for demos and dev.

type Row = [string, string, Record<string, unknown>?];

const ROWS: Row[] = [
  // Energy
  ["sensor.victron_battery_soc", "76", { unit_of_measurement: "%" }],
  ["sensor.victron_battery_power", "-420", { unit_of_measurement: "W" }],
  ["sensor.victron_battery_state_text", "Discharging"],
  ["sensor.victron_battery_voltage", "52.2", { unit_of_measurement: "V" }],
  ["sensor.victron_battery_temperature", "20", { unit_of_measurement: "°C" }],
  ["sensor.victron_total_pv_power", "1850", { unit_of_measurement: "W" }],
  ["sensor.victron_total_pv_yield_today", "6.4", { unit_of_measurement: "kWh" }],
  ["sensor.victron_grid_total_power", "10", { unit_of_measurement: "W" }],
  ["sensor.victron_grid_import_today", "3.15", { unit_of_measurement: "kWh" }],
  ["sensor.victron_ac_consumption_l1", "1430", { unit_of_measurement: "W" }],
  ["sensor.victron_essential_loads", "840", { unit_of_measurement: "W" }],
  ["sensor.victron_inverter_state_text", "Bulk"],
  ["sensor.grid_independence_today", "87.4", { unit_of_measurement: "%" }],
  ["sensor.grid_independence_this_month", "73.5", { unit_of_measurement: "%" }],
  ["sensor.grid_free_night_streak", "41"],
  ["sensor.solar_yield_today", "6.4", { unit_of_measurement: "kWh" }],
  ["sensor.solar_yield_this_week", "42.7", { unit_of_measurement: "kWh" }],
  ["sensor.solar_yield_this_month", "154.5", { unit_of_measurement: "kWh" }],
  ["sensor.total_solar_savings", "32324", { unit_of_measurement: "R" }],
  ["sensor.battery_health_score", "100", { unit_of_measurement: "%" }],
  ["sensor.energy_cost_today", "100.24", { unit_of_measurement: "R" }],
  ["sensor.energy_cost_projected_monthly", "2659", { unit_of_measurement: "R" }],
  ["sensor.energy_report_card", "B"],
  ["sensor.victron_grid_lost_alarm", "0"],

  // Water
  ["sensor.jojo_tank_monitor_tank_water_level", "99.1", { unit_of_measurement: "%" }],
  ["sensor.jojo_tank_monitor_tank_water_volume", "9910", { unit_of_measurement: "L" }],
  ["sensor.jojo_tank_monitor_tank_status", "Full"],
  ["sensor.jojo_tank_days_remaining", "72.9", { unit_of_measurement: "days" }],
  ["binary_sensor.jojo_tank_monitor_tank_low_water_alert", "off"],
  ["sensor.water_used_today", "117", { unit_of_measurement: "L" }],
  ["sensor.water_used_yesterday", "136", { unit_of_measurement: "L" }],
  ["sensor.average_daily_water_usage_7_days", "125", { unit_of_measurement: "L" }],
  ["sensor.borehole_pump_water_pumped_today", "186", { unit_of_measurement: "L" }],
  ["sensor.borehole_pump_water_pumped_this_month", "31456", { unit_of_measurement: "L" }],
  ["sensor.borehole_pump_status", "Idle"],
  ["sensor.pool_pump_status", "Idle"],
  ["sensor.water_pump_power", "3", { unit_of_measurement: "W" }],

  // Climate
  ["sensor.indoor_average_temperature", "16.0", { unit_of_measurement: "°C" }],
  ["weather.home", "clear-night", { temperature: 14 }],
  ["sensor.main_room_temperature", "16.7", { unit_of_measurement: "°C" }],
  ["sensor.liam_s_room_temperature", "16.68", { unit_of_measurement: "°C" }],
  ["sensor.kitchen_sensor_temperature", "15.94", { unit_of_measurement: "°C" }],
  ["sensor.living_room_sensor_temperature", "15.41", { unit_of_measurement: "°C" }],
  ["sensor.study_temperature", "17.8", { unit_of_measurement: "°C" }],
  ["sensor.patio_sensor_temperature", "13.98", { unit_of_measurement: "°C" }],
  ["sensor.back_yard_temperature", "12.1", { unit_of_measurement: "°C" }],
  ["sensor.main_bedroom_lamp_si7021_humidity", "68.5", { unit_of_measurement: "%" }],
  ["sensor.liam_s_room_humidity", "60.3", { unit_of_measurement: "%" }],
  ["sensor.kitchen_sensor_humidity", "69.1", { unit_of_measurement: "%" }],
  ["sensor.living_room_sensor_humidity", "68.2", { unit_of_measurement: "%" }],
  ["sensor.patio_sensor_humidity", "64.1", { unit_of_measurement: "%" }],

  // Security
  ["alarm_control_panel.olarm_alarm", "disarmed"],
  ["alarm_control_panel.olarm_beams", "disarmed"],
  ["alarm_control_panel.helloliam_alarm_area_01_huis", "disarmed"],
  ["binary_sensor.helloliam_alarm_ac_power", "on"],
  ["sensor.alarm_bypassed_zones_2", "0"],
  ["binary_sensor.helloliam_alarm_zone_013_front_door", "off"],
  ["binary_sensor.helloliam_alarm_zone_020_door_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_024_door_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_016_lounge_windows", "off"],
  ["binary_sensor.helloliam_alarm_zone_015_beam_driveway", "off"],
  ["binary_sensor.helloliam_alarm_zone_018_beam_pool", "off"],
  ["binary_sensor.helloliam_alarm_zone_022_beam_back_garden", "on"],
  ["binary_sensor.helloliam_alarm_zone_023_beam_patio", "off"],
  ["binary_sensor.helloliam_alarm_zone_030_beam_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_006_beam_gate_to_back", "off"],

  // Lights
  ["switch.kitchen_lights", "off"],
  ["switch.kitchen_under_counter_lights", "on"],
  ["switch.living_room_lamp", "off"],
  ["switch.tv_room_lamp", "off"],
  ["switch.main_bedroom_lamp", "on"],
  ["light.study_lamp", "on"],
  ["group.room_lamps", "on"],
  ["group.lounge_lamps", "off"],
  ["light.street_lights", "on"],
  ["switch.driveway_lights_switch", "off"],
  ["switch.gate_spotlight", "off"],
  ["light.back_yard_fire_pit_light", "on"],
  ["light.study_yard_light", "off"],

  // Pumps
  ["switch.water_pump", "on"],
  ["switch.pool_pump", "off"],
  ["switch.borehole_pump", "off"],

  // Appliances
  ["switch.dishwasher", "on"],
  ["sensor.dishwasher_power", "0", { unit_of_measurement: "W" }],
  ["switch.washing_machine", "on"],
  ["sensor.washing_machine_energy_power", "2", { unit_of_measurement: "W" }],
  ["switch.tumble_dryer", "on"],
  ["sensor.tumble_dryer_energy_power", "0", { unit_of_measurement: "W" }],
  ["switch.kettle", "on"],
  ["sensor.kettle_power", "0", { unit_of_measurement: "W" }],
  ["switch.microwave", "on"],
  ["sensor.microwave_current_consumption", "0.8", { unit_of_measurement: "W" }],
  ["switch.kitchen_air_fryer", "on"],
  ["sensor.kitchen_air_fryer_power", "0", { unit_of_measurement: "W" }],
  ["switch.nespresso", "on"],
  ["sensor.nespresso_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.work_pc", "on"],
  ["sensor.work_pc_current_consumption", "202", { unit_of_measurement: "W" }],
  ["switch.study_heater", "off"],
  ["sensor.study_heater_current_consumption", "0", { unit_of_measurement: "W" }],

  // Traffic
  ["sensor.vehicles_today", "935"],
  ["sensor.vehicles_this_week", "3582"],
  ["sensor.vehicles_this_month", "7232"],
  ["sensor.pedestrians_today", "50"],
  ["sensor.pedestrians_this_week", "427"],
  ["sensor.pedestrians_this_month", "2098"],
  ["counter.frigate_main_gate_detections_today", "22"],
  ["counter.frigate_person_detections_today", "1"],
  ["counter.frigate_vehicle_detections_today", "21"],
  ["sensor.main_gate_ai_last_recognized_plate", "None"],
  ["sensor.sidewalk_traffic_intensity", "Moderate"],
  ["sensor.sidewalk_morning_traffic", "19"],
  ["sensor.sidewalk_afternoon_traffic", "9"],
  ["sensor.sidewalk_evening_traffic", "4"],
  ["sensor.sidewalk_night_traffic", "1"],

  // System
  ["sensor.fibre_router_cpu_usage", "3.3", { unit_of_measurement: "%" }],
  ["sensor.fibre_router_memory_usage", "91.1", { unit_of_measurement: "%" }],
  ["sensor.fibre_router_devices_connected", "40"],
  ["sensor.fibre_router_download_speed", "94.2", { unit_of_measurement: "Mbit/s" }],
  ["sensor.fibre_router_upload_speed", "38.1", { unit_of_measurement: "Mbit/s" }],
  ["sensor.fibre_router_uptime", "3593823", { unit_of_measurement: "s" }],
  ["sensor.low_battery_devices", "1"],
  ["sensor.total_monitored_loads", "274", { unit_of_measurement: "W" }],
  ["sensor.estimated_unmonitored_loads", "540", { unit_of_measurement: "W" }],
  ["sensor.brother_dcp_t720dw", "idle"],
  ["sensor.brother_dcp_t720dw_bk", "43", { unit_of_measurement: "%" }],
  ["sensor.brother_dcp_t720dw_c", "31", { unit_of_measurement: "%" }],
  ["sensor.brother_dcp_t720dw_m", "37", { unit_of_measurement: "%" }],
  ["sensor.brother_dcp_t720dw_y", "31", { unit_of_measurement: "%" }],
  ["device_tracker.kitchen_deco", "home"],
  ["device_tracker.main_living_room_deco", "home"],
  ["device_tracker.study_deco", "home"],
  ["sensor.victron_mppt1_pv_power", "0", { unit_of_measurement: "W" }],
  ["sensor.victron_mppt2_pv_power", "0", { unit_of_measurement: "W" }],

  // Occupancy / people
  ["sensor.home_occupancy", "Occupied"],
  ["binary_sensor.house_occupied", "on"],
  ["binary_sensor.house_interior_motion", "on"],
  ["binary_sensor.nobody_home", "off"],
  ["person.christo_steyn", "home"],
  ["person.mandri_steyn", "not_home"],
  ["person.hello_liam_en_eben", "home"],

  // Access door/beam sensors
  ["binary_sensor.helloliam_alarm_zone_020_door_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_024_door_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_030_beam_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_006_beam_gate_to_back", "off"],

  // Irrigation (Wyze)
  ["sensor.helloeben_sprinkler_current_zone", "Idle"],
  ["input_select.irrigation_zone_selector", "Front Lawn", { options: ["Front Lawn", "Back Garden", "Veggie Patch", "Flower Beds", "Driveway Strip", "Rose Garden"] }],
  ["input_number.irrigation_runtime_minutes", "10", { unit_of_measurement: "min" }],
  ["input_boolean.irrigation_intelligence_enabled", "on"],
  ["sensor.sprinkler_watering_time_today", "18", { unit_of_measurement: "min" }],
  ["sensor.sprinkler_watering_time_this_month", "420", { unit_of_measurement: "min" }],

  // Settings inputs
  ["input_boolean.alarm_auto_arm_away", "off"],
  ["input_boolean.alarm_auto_arm_stay", "off"],
  ["input_boolean.alarm_auto_arm_beams", "on"],
  ["input_boolean.alarm_auto_disarm", "on"],
  ["input_boolean.alarm_auto_disarm_beams", "on"],
  ["input_datetime.alarm_auto_arm_away_time", "17:00:00"],
  ["input_datetime.alarm_auto_arm_stay_time", "22:00:00"],
  ["input_datetime.alarm_auto_arm_time_beams", "22:10:00"],
  ["input_datetime.alarm_auto_disarm_time", "06:00:00"],
  ["input_datetime.alarm_auto_disarm_time_beams", "06:05:00"],
  ["input_boolean.frigate_person_detection_enabled", "on"],
  ["input_boolean.frigate_vehicle_detection_enabled", "on"],
  ["input_boolean.door_open_alerts_enabled", "on"],
  ["input_select.zone_bypass_selector", "None", { options: ["None", "Zone 22: Beam - Back Garden", "Zone 18: Beam - Pool", "Zone 15: Beam - Driveway"] }],

  // Cameras
  ["camera.main_gate", "recording"],
  ["camera.driveway", "idle"],
  ["camera.gate_outside", "idle"],
  ["camera.sidewalk_ai", "recording"],
  ["camera.store_room", "idle"],
  ["camera.ids_7216hqhi_m1_s1620231215ccwray1010746wcvu_201", "idle"],
  ["camera.ids_7216hqhi_m1_s1620231215ccwray1010746wcvu_301", "idle"],
  ["camera.ids_7216hqhi_m1_s1620231215ccwray1010746wcvu_501", "idle"],

  // Oura (health)
  ["sensor.oura_sleep_score", "82"],
  ["sensor.oura_readiness_score", "80"],
  ["sensor.oura_activity_score", "76"],
  ["sensor.oura_total_sleep_duration", "25920", { unit_of_measurement: "s" }],
  ["sensor.oura_time_in_bed", "28800", { unit_of_measurement: "s" }],
  ["sensor.oura_deep_sleep_duration", "5400", { unit_of_measurement: "s" }],
  ["sensor.oura_rem_sleep_duration", "6000", { unit_of_measurement: "s" }],
  ["sensor.oura_light_sleep_duration", "13020", { unit_of_measurement: "s" }],
  ["sensor.oura_awake_time", "1500", { unit_of_measurement: "s" }],
  ["sensor.oura_sleep_efficiency", "91", { unit_of_measurement: "%" }],
  ["sensor.oura_restfulness", "78", { unit_of_measurement: "%" }],
  ["sensor.oura_sleep_latency", "720", { unit_of_measurement: "s" }],
  ["sensor.oura_average_sleep_heart_rate", "54", { unit_of_measurement: "bpm" }],
  ["sensor.oura_average_sleep_hrv", "42", { unit_of_measurement: "ms" }],
  ["sensor.oura_current_heart_rate", "62", { unit_of_measurement: "bpm" }],
  ["sensor.oura_lowest_sleep_heart_rate", "51", { unit_of_measurement: "bpm" }],
  ["sensor.oura_steps", "6400"],
  ["sensor.oura_active_calories", "420", { unit_of_measurement: "kcal" }],
  ["sensor.oura_total_calories", "2360", { unit_of_measurement: "kcal" }],
  ["sensor.oura_target_calories", "500", { unit_of_measurement: "kcal" }],
  ["sensor.oura_low_activity_time", "18000", { unit_of_measurement: "s" }],
  ["sensor.oura_ring_battery_level", "68", { unit_of_measurement: "%" }],
  ["sensor.oura_bedtime_start", "2026-07-10T22:40:00+02:00"],
  ["sensor.oura_temperature_deviation", "0.2", { unit_of_measurement: "°C" }],
];

export const MOCK: HassEntities = Object.fromEntries(
  ROWS.map(([id, state, attrs]) => [
    id,
    {
      entity_id: id,
      state,
      attributes: { friendly_name: id, ...(attrs ?? {}) },
      last_changed: "",
      last_updated: "",
      context: { id: "", user_id: null, parent_id: null },
    },
  ]),
) as unknown as HassEntities;
