import type { HassEntities } from "./ha";

// Realistic offline dataset (values from DASHBOARD_DATA_SNAPSHOT.md, with a
// few tweaked to daytime so charts/flow look alive). Enabled with ?mock=1 —
// lets the UI run with no Home Assistant connection, for demos and dev.

type Row = [string, string, Record<string, unknown>?];

const ROWS: Row[] = [
  // Energy
  ["sensor.victron_battery_soc", "76", { unit_of_measurement: "%" }],
  ["sensor.victron_battery_power", "-420", { unit_of_measurement: "W" }],
  ["sensor.victron_battery_state_text", "Discharging"],
  ["sensor.victron_battery_voltage", "52.2", { unit_of_measurement: "V" }],
  ["sensor.victron_battery_temperature", "20", { unit_of_measurement: "°C" }],
  ["sensor.victron_total_pv_power", "1850", { unit_of_measurement: "W" }],
  ["sensor.victron_total_pv_yield_today", "6.4", { unit_of_measurement: "kWh" }],
  ["sensor.victron_grid_total_power", "10", { unit_of_measurement: "W" }],
  ["sensor.victron_grid_import_today", "3.15", { unit_of_measurement: "kWh" }],
  ["sensor.victron_ac_consumption_l1", "1430", { unit_of_measurement: "W" }],
  ["sensor.victron_essential_loads", "840", { unit_of_measurement: "W" }],
  ["sensor.victron_inverter_state_text", "Bulk"],
  ["sensor.grid_independence_today", "87.4", { unit_of_measurement: "%" }],
  ["sensor.energy_action_banner", "Solar surplus — good time to run the dishwasher or pool pump", { level: "good", icon: "mdi:bullhorn" }],
  ["sensor.self_sufficiency_today", "76", { unit_of_measurement: "%" }],
  ["sensor.solar_saved_today", "55.44", { unit_of_measurement: "ZAR" }],
  ["sensor.consumption_expected_today", "25.6", { unit_of_measurement: "kWh" }],
  ["sensor.consumption_vs_expected", "-2.0", { unit_of_measurement: "kWh" }],
  ["sensor.mppt_string_health", "ok"],
  ["sensor.battery_value_now", "0.0", { unit_of_measurement: "R/h" }],
  ["sensor.battery_tou_status", "neutral"],
  ["binary_sensor.solar_surplus_window_open", "on"],
  ["sensor.borehole_efficiency_today", "1077", { unit_of_measurement: "L/kWh" }],
  ["sensor.borehole_efficiency_30d", "976", { unit_of_measurement: "L/kWh" }],
  ["sensor.system_health_issues", "0"],
  ["binary_sensor.frigate_detection_stalled", "off"],
  ["sensor.battery_cell_temp_spread", "6.0", { unit_of_measurement: "°C" }],
  ["binary_sensor.study_occupancy", "on"],
  ["binary_sensor.lounge_area_occupancy", "off"],
  ["sensor.dining_room_lamp_power", "0", { unit_of_measurement: "W" }],
  ["sensor.eben_room_lamp_power", "4", { unit_of_measurement: "W" }],
  ["sensor.study_yard_light_power", "0", { unit_of_measurement: "W" }],
  ["sensor.pool_light_power", "0", { unit_of_measurement: "W" }],
  ["input_boolean.borehole_night_guard_enabled", "on"],
  ["input_boolean.frigate_watchdog_enabled", "on"],
  ["input_boolean.light_watchdog_enabled", "on"],
  ["input_boolean.appliance_finish_alerts_enabled", "on"],
  ["input_boolean.window_advisor_enabled", "on"],
  ["input_boolean.fridge_open_alert_enabled", "on"],
  ["input_boolean.desk_comfort_enabled", "off"],
  ["input_boolean.evening_lights_enabled", "on"],
  ["input_boolean.night_kitchen_light_enabled", "on"],
  ["input_boolean.holiday_mode", "off"],
  ["sensor.grid_independence_this_month", "73.5", { unit_of_measurement: "%" }],
  ["sensor.grid_free_night_streak", "41"],
  ["sensor.solar_yield_today", "6.4", { unit_of_measurement: "kWh" }],
  ["sensor.solar_yield_this_week", "42.7", { unit_of_measurement: "kWh" }],
  ["sensor.solar_yield_this_month", "154.5", { unit_of_measurement: "kWh" }],
  ["sensor.total_solar_savings", "32324", { unit_of_measurement: "R" }],
  ["sensor.battery_health_score", "100", { unit_of_measurement: "%" }],
  ["sensor.energy_cost_today", "100.24", { unit_of_measurement: "R" }],
  ["sensor.energy_cost_projected_monthly", "2659", { unit_of_measurement: "R" }],
  ["sensor.energy_report_card", "B"],
  ["sensor.victron_grid_lost_alarm", "0"],

  // Water
  ["sensor.jojo_tank_monitor_tank_water_level", "99.1", { unit_of_measurement: "%" }],
  ["sensor.jojo_tank_monitor_tank_water_volume", "9910", { unit_of_measurement: "L" }],
  ["sensor.jojo_tank_monitor_tank_status", "Full"],
  ["sensor.jojo_tank_days_remaining", "72.9", { unit_of_measurement: "days" }],
  ["binary_sensor.jojo_tank_monitor_tank_low_water_alert", "off"],
  ["sensor.water_used_today", "117", { unit_of_measurement: "L" }],
  ["sensor.water_used_yesterday", "136", { unit_of_measurement: "L" }],
  ["sensor.average_daily_water_usage_7_days", "125", { unit_of_measurement: "L" }],
  ["sensor.borehole_pump_water_pumped_today", "186", { unit_of_measurement: "L" }],
  ["sensor.borehole_pump_water_pumped_this_month", "31456", { unit_of_measurement: "L" }],
  ["sensor.borehole_pump_status", "Idle"],
  ["sensor.pool_pump_status", "Idle"],
  ["sensor.water_pump_power", "3", { unit_of_measurement: "W" }],

  // Climate
  ["sensor.indoor_average_temperature", "16.0", { unit_of_measurement: "°C" }],
  ["sensor.outdoor_temperature", "20.4", { unit_of_measurement: "°C" }],
  ["sensor.outdoor_humidity", "21", { unit_of_measurement: "%" }],
  ["sensor.outdoor_forecast_temperature", "19.0", { unit_of_measurement: "°C" }],
  ["sensor.outdoor_temp_vs_forecast", "1.4", { unit_of_measurement: "°C" }],
  ["sensor.home_integrity", "2", { issues: [
    { area: "water", msg: "Possible water leak", detail: "Tank draining 45 L/h with no tap use and borehole off" },
    { area: "system", msg: "Sensor(s) faulty/stale", detail: "Guest Room Temperature (stale 5h)" },
  ] }],
  ["weather.home", "clear-night", { temperature: 14 }],
  ["sensor.main_room_temperature", "16.7", { unit_of_measurement: "°C" }],
  ["sensor.liam_s_room_temperature", "16.68", { unit_of_measurement: "°C" }],
  ["sensor.kitchen_sensor_temperature", "15.94", { unit_of_measurement: "°C" }],
  ["sensor.living_room_sensor_temperature", "15.41", { unit_of_measurement: "°C" }],
  ["sensor.study_temperature", "17.8", { unit_of_measurement: "°C" }],
  ["sensor.study_bt_device_scanner_desk_temperature", "14.7", { unit_of_measurement: "°C" }],
  ["sensor.study_bt_device_scanner_desk_humidity", "26.6", { unit_of_measurement: "%" }],
  ["sensor.study_bt_device_scanner_desk_pressure", "863.9", { unit_of_measurement: "hPa" }],
  ["sensor.patio_sensor_temperature", "13.98", { unit_of_measurement: "°C" }],
  ["sensor.back_yard_temperature", "12.1", { unit_of_measurement: "°C" }],
  ["sensor.adjusted_temperature", "15.4", { unit_of_measurement: "°C" }],
  ["sensor.guest_room_temperature", "16.2", { unit_of_measurement: "°C" }],
  ["sensor.main_bedroom_lamp_si7021_humidity", "68.5", { unit_of_measurement: "%" }],
  ["sensor.liam_s_room_humidity", "60.3", { unit_of_measurement: "%" }],
  ["sensor.kitchen_sensor_humidity", "69.1", { unit_of_measurement: "%" }],
  ["sensor.living_room_sensor_humidity", "68.2", { unit_of_measurement: "%" }],
  ["sensor.patio_sensor_humidity", "64.1", { unit_of_measurement: "%" }],

  // Security
  ["alarm_control_panel.olarm_alarm", "disarmed"],
  ["alarm_control_panel.olarm_beams", "disarmed"],
  ["alarm_control_panel.helloliam_alarm_area_01_huis", "disarmed"],
  ["alarm_control_panel.helloliam_alarm_area_02_beams", "disarmed"],
  ["binary_sensor.helloliam_alarm_ac_power", "on"],
  ["sensor.alarm_bypassed_zones_2", "0"],
  // All 31 zones + per-zone bypass status (022 active, 019 bypassed for demo)
  ["binary_sensor.helloliam_alarm_zone_001_panic", "off"],
  ["binary_sensor.helloliam_alarm_zone_001_bypass_panic", "off"],
  ["binary_sensor.helloliam_alarm_zone_002_pir_guest_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_002_bypass_pir_guest_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_003_pir_kids_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_003_bypass_pir_kids_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_004_remote_p1_p2", "off"],
  ["binary_sensor.helloliam_alarm_zone_004_bypass_remote_p1_p2", "off"],
  ["binary_sensor.helloliam_alarm_zone_005_remote_p1", "off"],
  ["binary_sensor.helloliam_alarm_zone_005_bypass_remote_p1", "off"],
  ["binary_sensor.helloliam_alarm_zone_006_beam_gate_to_back", "off"],
  ["binary_sensor.helloliam_alarm_zone_006_bypass_beam_gate_to_back", "off"],
  ["binary_sensor.helloliam_alarm_zone_007_pir_tv_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_007_bypass_pir_tv_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_008_pir_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_008_bypass_pir_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_009_pir_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_009_bypass_pir_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_010_pir_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_010_bypass_pir_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_011_beam_back_gas", "off"],
  ["binary_sensor.helloliam_alarm_zone_011_bypass_beam_back_gas", "off"],
  ["binary_sensor.helloliam_alarm_zone_012_beam_store_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_012_bypass_beam_store_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_013_front_door", "off"],
  ["binary_sensor.helloliam_alarm_zone_013_bypass_front_door", "off"],
  ["binary_sensor.helloliam_alarm_zone_014_pir_front_door", "off"],
  ["binary_sensor.helloliam_alarm_zone_014_bypass_pir_front_door", "off"],
  ["binary_sensor.helloliam_alarm_zone_015_beam_driveway", "off"],
  ["binary_sensor.helloliam_alarm_zone_015_bypass_beam_driveway", "off"],
  ["binary_sensor.helloliam_alarm_zone_016_lounge_windows", "off"],
  ["binary_sensor.helloliam_alarm_zone_016_bypass_lounge_windows", "off"],
  ["binary_sensor.helloliam_alarm_zone_017_beam_bedroom_windows", "off"],
  ["binary_sensor.helloliam_alarm_zone_017_bypass_beam_bedroom_windows", "off"],
  ["binary_sensor.helloliam_alarm_zone_018_beam_pool", "off"],
  ["binary_sensor.helloliam_alarm_zone_018_bypass_beam_pool", "off"],
  ["binary_sensor.helloliam_alarm_zone_019_pir_roof", "off"],
  ["binary_sensor.helloliam_alarm_zone_019_bypass_pir_roof", "on"],
  ["binary_sensor.helloliam_alarm_zone_020_door_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_020_bypass_door_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_021_pir_passage", "off"],
  ["binary_sensor.helloliam_alarm_zone_021_bypass_pir_passage", "off"],
  ["binary_sensor.helloliam_alarm_zone_022_beam_back_garden", "on"],
  ["binary_sensor.helloliam_alarm_zone_022_bypass_beam_back_garden", "off"],
  ["binary_sensor.helloliam_alarm_zone_023_beam_patio", "off"],
  ["binary_sensor.helloliam_alarm_zone_023_bypass_beam_patio", "off"],
  ["binary_sensor.helloliam_alarm_zone_024_door_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_024_bypass_door_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_025_pir_main_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_025_bypass_pir_main_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_026_zone_26", "off"],
  ["binary_sensor.helloliam_alarm_zone_026_bypass_zone_26", "off"],
  ["binary_sensor.helloliam_alarm_zone_027_zone_27", "off"],
  ["binary_sensor.helloliam_alarm_zone_027_bypass_zone_27", "off"],
  ["binary_sensor.helloliam_alarm_zone_028_zone_28", "off"],
  ["binary_sensor.helloliam_alarm_zone_028_bypass_zone_28", "off"],
  ["binary_sensor.helloliam_alarm_zone_029_zone_29", "off"],
  ["binary_sensor.helloliam_alarm_zone_029_bypass_zone_29", "off"],
  ["binary_sensor.helloliam_alarm_zone_030_beam_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_030_bypass_beam_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_031_zone_31", "off"],
  ["binary_sensor.helloliam_alarm_zone_031_bypass_zone_31", "off"],

  // Lights (supported_color_modes drives whether a tile gets the brightness sheet)
  ["switch.kitchen_lights", "off"],
  ["switch.kitchen_under_counter_lights", "on"],
  ["switch.living_room_lamp", "off"],
  ["switch.tv_room_lamp", "off"],
  ["light.dining_room_lamp", "off", { supported_color_modes: ["onoff"] }],
  ["group.lounge_lamps", "off", { entity_id: ["switch.living_room_lamp", "switch.tv_room_lamp", "light.dining_room_lamp"] }],
  ["switch.main_bedroom_lamp", "on"],
  ["light.main_bedroom_light", "off", { supported_color_modes: ["onoff"] }],
  ["light.main_bedroom_dresser_light", "off", { supported_color_modes: ["onoff"] }],
  ["light.eben_room_lamp", "off", { supported_color_modes: ["onoff"] }],
  ["switch.guest_room", "off"],
  ["group.room_lamps", "on", { entity_id: ["switch.main_bedroom_lamp", "light.eben_room_lamp", "switch.guest_room"] }],
  ["light.study_lamp", "on", { supported_color_modes: ["onoff"] }],
  ["light.study_light_1", "on", { supported_color_modes: ["color_temp", "rgb"], brightness: 204 }],
  ["light.study_light_2", "off", { supported_color_modes: ["color_temp", "rgb"] }],
  ["light.street_lights", "on", { supported_color_modes: ["onoff"] }],
  ["switch.driveway_lights_switch", "off"],
  ["switch.gate_spotlight", "off"],
  ["switch.patio_lamp", "off"],
  ["light.back_yard_pool_light", "off", { supported_color_modes: ["brightness"] }],
  ["light.back_yard_fire_pit_light", "on", { supported_color_modes: ["color_temp", "rgb"], brightness: 180 }],
  ["light.study_yard_light", "off", { supported_color_modes: ["color_temp", "hs"] }],

  // Pumps
  ["switch.water_pump", "on"],
  ["switch.pool_pump", "off"],
  ["switch.borehole_pump", "off"],

  // Appliances
  ["switch.main_fridge", "on"],
  ["sensor.main_fridge_current_consumption", "118", { unit_of_measurement: "W" }],
  ["switch.dishwasher", "on"],
  ["sensor.dishwasher_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.washing_machine", "on"],
  ["sensor.washing_machine_energy_power", "2", { unit_of_measurement: "W" }],
  ["switch.top_loader", "off"],
  ["sensor.top_loader_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.tumble_dryer", "on"],
  ["sensor.tumble_dryer_energy_power", "0", { unit_of_measurement: "W" }],
  ["switch.kettle", "on"],
  ["sensor.kettle_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.microwave", "on"],
  ["sensor.microwave_current_consumption", "0.8", { unit_of_measurement: "W" }],
  ["switch.air_fryer", "on"],
  ["sensor.air_fryer_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.nespresso", "on"],
  ["sensor.nespresso_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.work_pc", "on"],
  ["sensor.work_pc_current_consumption", "202", { unit_of_measurement: "W" }],
  ["switch.study_heater", "off"],
  ["sensor.study_heater_current_consumption", "0", { unit_of_measurement: "W" }],
  ["switch.dining_room_alarm_cctv_power_monitor", "on"],
  ["sensor.dining_room_alarm_cctv_power_monitor_power", "48", { unit_of_measurement: "W" }],
  ["switch.living_room_main_tv_plug", "on"],
  ["sensor.living_room_main_tv_plug_power", "23.8", { unit_of_measurement: "W" }],
  ["switch.study_router_and_ha", "on"],
  ["sensor.study_router_and_ha_power", "55.6", { unit_of_measurement: "W" }],
  ["switch.main_bedroom_plugs", "on"],
  ["sensor.main_bedroom_plugs_current_consumption", "18.8", { unit_of_measurement: "W" }],
  ["switch.hallway_bedroom_and_living_room_lights", "on"],
  ["sensor.hallway_bedroom_and_living_room_lights_power", "81", { unit_of_measurement: "W" }],
  ["light.street_lights", "on"],
  ["sensor.street_lights_street_lights_power", "62.8", { unit_of_measurement: "W" }],

  // Traffic
  ["sensor.vehicles_today", "935"],
  ["sensor.vehicles_this_week", "3582"],
  ["sensor.vehicles_this_month", "7232"],
  ["sensor.pedestrians_today", "50"],
  ["sensor.pedestrians_this_week", "427"],
  ["sensor.pedestrians_this_month", "2098"],
  ["counter.frigate_main_gate_detections_today", "22"],
  ["counter.frigate_person_detections_today", "1"],
  ["counter.frigate_vehicle_detections_today", "21"],
  ["sensor.main_gate_ai_last_recognized_plate", "CA 371-905"],
  ["input_text.known_vehicle_plates", "CA 214-882=Christo,CA 118-540=Mandri,WK 09-JHB=Mom"],
  ["sensor.main_gate_plate_owner", ""],
  ["binary_sensor.main_gate_ai_person_occupancy", "off"],
  ["input_number.electricity_tariff", "4.05", { unit_of_measurement: "R/kWh" }],
  // InfluxQL server-side trend baselines (90d) + recent (7d)
  ["sensor.standby_power_90d_baseline", "92", { unit_of_measurement: "W" }],
  ["sensor.standby_power_7d_recent", "86", { unit_of_measurement: "W" }],
  ["sensor.baseline_load_90d_baseline", "96", { unit_of_measurement: "W" }],
  ["sensor.baseline_load_7d_recent", "97", { unit_of_measurement: "W" }],
  ["sensor.water_use_90d_baseline", "125", { unit_of_measurement: "L" }],
  ["sensor.water_use_7d_recent", "116", { unit_of_measurement: "L" }],
  ["input_number.water_use_baseline", "118"],
  ["input_number.grid_import_baseline", "3.4"],
  ["input_number.trend_watch_days", "22"],
  ["sensor.sidewalk_traffic_intensity", "Moderate"],
  ["sensor.sidewalk_morning_traffic", "19"],
  ["sensor.sidewalk_afternoon_traffic", "9"],
  ["sensor.sidewalk_evening_traffic", "4"],
  ["sensor.sidewalk_night_traffic", "1"],

  // System
  ["sensor.fibre_router_cpu_usage", "3.3", { unit_of_measurement: "%" }],
  ["sensor.fibre_router_memory_usage", "91.1", { unit_of_measurement: "%" }],
  ["sensor.fibre_router_devices_connected", "40"],
  ["sensor.fibre_router_download_speed", "94.2", { unit_of_measurement: "Mbit/s" }],
  ["sensor.fibre_router_upload_speed", "38.1", { unit_of_measurement: "Mbit/s" }],
  ["sensor.fibre_router_uptime", "3593823", { unit_of_measurement: "s" }],
  ["sensor.low_battery_devices", "1"],
  ["sensor.total_monitored_loads", "274", { unit_of_measurement: "W" }],
  ["sensor.estimated_unmonitored_loads", "540", { unit_of_measurement: "W" }],
  ["sensor.power_reconciliation", "85", { unit_of_measurement: "%", data: {
    total_w: 1476, accounted_w: 1256, unknown_w: 220, pct: 85,
    devices: [
      { name: "Aircons & oven", w: 480 },
      { name: "Study heater", w: 300 },
      { name: "Main fridge", w: 165 },
      { name: "Main PC", w: 120 },
      { name: "Alarm & CCTV", w: 60 },
      { name: "Outdoor lights", w: 55 },
      { name: "Kitchen lights", w: 45 },
      { name: "TV room lamp", w: 28 },
      { name: "Water pump", w: 3 },
    ],
    warnings: [],
  } }],
  ["sensor.energy_cost_attribution", "38.60", { unit_of_measurement: "ZAR", data: {
    tariff: 3.5, total_kwh: 11.03, total_cost: 38.6,
    devices: [
      { name: "Tumble dryer", kwh: 3.2, cost: 11.2 },
      { name: "Study heater", kwh: 2.4, cost: 8.4 },
      { name: "Main fridge", kwh: 1.8, cost: 6.3 },
      { name: "Washing machine", kwh: 1.1, cost: 3.85 },
      { name: "Kettle", kwh: 0.9, cost: 3.15 },
      { name: "Main PC", kwh: 0.75, cost: 2.63 },
      { name: "Dishwasher", kwh: 0.5, cost: 1.75 },
      { name: "Alarm & CCTV", kwh: 0.28, cost: 0.98 },
      { name: "Microwave", kwh: 0.1, cost: 0.35 },
    ],
    warnings: [],
  } }],
  ["sensor.brother_dcp_t720dw", "idle"],
  ["sensor.brother_dcp_t720dw_bk", "43", { unit_of_measurement: "%" }],
  ["sensor.brother_dcp_t720dw_c", "31", { unit_of_measurement: "%" }],
  ["sensor.brother_dcp_t720dw_m", "37", { unit_of_measurement: "%" }],
  ["sensor.brother_dcp_t720dw_y", "31", { unit_of_measurement: "%" }],
  ["device_tracker.kitchen_deco", "home"],
  ["device_tracker.main_living_room_deco", "home"],
  ["device_tracker.study_deco", "home"],
  ["sensor.victron_mppt1_pv_power", "0", { unit_of_measurement: "W" }],
  ["sensor.victron_mppt2_pv_power", "0", { unit_of_measurement: "W" }],

  // Occupancy / people
  ["sensor.home_occupancy", "Occupied"],
  ["binary_sensor.house_occupied", "on"],
  ["binary_sensor.house_interior_motion", "on"],
  ["binary_sensor.nobody_home", "off"],
  ["person.christo_steyn", "home"],
  ["person.mandri_steyn", "not_home"],
  ["person.hello_liam_en_eben", "home"],

  // Access door/beam sensors
  ["binary_sensor.helloliam_alarm_zone_020_door_kitchen", "off"],
  ["binary_sensor.helloliam_alarm_zone_024_door_lounge", "off"],
  ["binary_sensor.helloliam_alarm_zone_030_beam_garage", "off"],
  ["binary_sensor.helloliam_alarm_zone_006_beam_gate_to_back", "off"],

  // Irrigation (Wyze / HelloEben)
  ["sensor.helloeben_sprinkler_current_zone", "Idle"],
  ["input_select.irrigation_zone_selector", "Zone 1: Sidewalk", { options: ["Zone 1: Sidewalk", "Zone 2: Gate/Front Yard", "Zone 3: Front Garden", "Zone 4: Back Yard Grass", "Zone 5: Back Yard", "Zone 6: JoJo/Courtyard"] }],
  ["input_number.irrigation_runtime_minutes", "10", { unit_of_measurement: "min" }],
  ["input_boolean.irrigation_intelligence_enabled", "on"],
  ["sensor.sprinkler_watering_time_today", "18", { unit_of_measurement: "min" }],
  ["sensor.sprinkler_watering_time_this_month", "420", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_next_scheduled_run", "2026-07-12T05:00:00+00:00"],
  ["sensor.helloeben_sprinkler_active_schedules", "2"],
  ["sensor.helloeben_sprinkler_sidewalk_remaining_time", "0", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_sidewalk_soil_moisture", "19.8", { unit_of_measurement: "%" }],
  ["sensor.helloeben_sprinkler_sidewalk_last_watered", "2026-07-08T05:15:00+00:00"],
  ["sensor.helloeben_sprinkler_gate_front_yard_remaining_time", "6", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_gate_front_yard_soil_moisture", "8.0", { unit_of_measurement: "%" }],
  ["sensor.helloeben_sprinkler_gate_front_yard_last_watered", "2026-07-06T06:52:00+00:00"],
  ["sensor.helloeben_sprinkler_front_garden_remaining_time", "0", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_front_garden_soil_moisture", "2.8", { unit_of_measurement: "%" }],
  ["sensor.helloeben_sprinkler_front_garden_last_watered", "2026-07-06T06:15:00+00:00"],
  ["sensor.helloeben_sprinkler_back_yard_grass_remaining_time", "0", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_back_yard_grass_soil_moisture", "44.0", { unit_of_measurement: "%" }],
  ["sensor.helloeben_sprinkler_back_yard_grass_last_watered", "2026-07-08T05:55:35+00:00"],
  ["sensor.helloeben_sprinkler_back_yard_remaining_time", "0", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_back_yard_soil_moisture", "9.3", { unit_of_measurement: "%" }],
  ["sensor.helloeben_sprinkler_back_yard_last_watered", "2026-07-06T06:27:00+00:00"],
  ["sensor.helloeben_sprinkler_jojo_courtyard_remaining_time", "0", { unit_of_measurement: "min" }],
  ["sensor.helloeben_sprinkler_jojo_courtyard_soil_moisture", "0.0", { unit_of_measurement: "%" }],
  ["sensor.helloeben_sprinkler_jojo_courtyard_last_watered", "2026-07-08T15:47:23+00:00"],

  // Settings inputs
  ["input_boolean.alarm_auto_arm_away", "off"],
  ["input_boolean.alarm_auto_arm_stay", "off"],
  ["input_boolean.alarm_auto_arm_beams", "on"],
  ["input_boolean.alarm_auto_disarm", "on"],
  ["input_boolean.alarm_auto_disarm_beams", "on"],
  ["input_datetime.alarm_auto_arm_away_time", "17:00:00"],
  ["input_datetime.alarm_auto_arm_stay_time", "22:00:00"],
  ["input_datetime.alarm_auto_arm_time_beams", "22:10:00"],
  ["input_datetime.alarm_auto_disarm_time", "06:00:00"],
  ["input_datetime.alarm_auto_disarm_time_beams", "06:05:00"],
  ["input_number.oura_steps_goal", "8000", { min: 1000, max: 20000, step: 500 }],
  ["input_number.oura_readiness_low_threshold", "70", { min: 50, max: 90, step: 1 }],
  ["input_number.oura_temp_deviation_threshold", "0.5", { min: 0.1, max: 1.5, step: 0.1, unit_of_measurement: "°C" }],
  ["input_boolean.reminders_enabled", "on"],
  ["sensor.message_templates", "3", { templates: {
    goodnight: { label: "Goodnight", base: "Goodnight. Alarm is {alarm}. Sleep well.", announce: "", push_christo: "🌙 Night — alarm {alarm}.", wa_christo: "", wa_mandri: "", wa_liam_eben: "Night night! 🌙" },
    morning_briefing: { label: "Morning Briefing", base: "{greeting}. Battery {battery}%, tank {tank}%.", announce: "", push_christo: "", wa_christo: "", wa_mandri: "", wa_liam_eben: "" },
    coffee_ready: { label: "Coffee Ready", base: "Your coffee is ready. Enjoy!", announce: "", push_christo: "", wa_christo: "", wa_mandri: "", wa_liam_eben: "" },
  } }],
  ["input_text.msg_goodnight", "Goodnight. Inside lights are off and the alarm is {alarm}. Sleep well.", { friendly_name: "Msg: Goodnight" }],
  ["input_text.msg_morning_briefing", "{greeting}. Battery {battery} percent, tank {tank} percent, {indoor} degrees inside.", { friendly_name: "Msg: Morning Briefing" }],
  ["input_boolean.frigate_person_detection_enabled", "on"],
  ["input_boolean.frigate_vehicle_detection_enabled", "on"],
  ["input_boolean.door_open_alerts_enabled", "on"],
  ["input_select.zone_bypass_selector", "None", { options: ["None", "Zone 22: Beam - Back Garden", "Zone 18: Beam - Pool", "Zone 15: Beam - Driveway"] }],

  // Cameras
  ["camera.main_gate", "recording"],
  ["camera.gate_outside", "idle"],
  ["camera.sidewalk_ai", "recording"],
  ["camera.store_room", "idle"],
  ["camera.ids_7216hqhi_m1_s1620231215ccwray1010746wcvu_201", "idle"],
  ["camera.ids_7216hqhi_m1_s1620231215ccwray1010746wcvu_301", "idle"],
  ["camera.ids_7216hqhi_m1_s1620231215ccwray1010746wcvu_501", "idle"],

  // Oura (health)
  ["sensor.oura_sleep_score", "82"],
  ["sensor.oura_readiness_score", "80"],
  ["sensor.oura_activity_score", "76"],
  ["sensor.oura_total_sleep_duration", "25920", { unit_of_measurement: "s" }],
  ["sensor.oura_time_in_bed", "28800", { unit_of_measurement: "s" }],
  ["sensor.oura_deep_sleep_duration", "5400", { unit_of_measurement: "s" }],
  ["sensor.oura_rem_sleep_duration", "6000", { unit_of_measurement: "s" }],
  ["sensor.oura_light_sleep_duration", "13020", { unit_of_measurement: "s" }],
  ["sensor.oura_awake_time", "1500", { unit_of_measurement: "s" }],
  ["sensor.oura_sleep_efficiency", "91", { unit_of_measurement: "%" }],
  ["sensor.oura_restfulness", "78", { unit_of_measurement: "%" }],
  ["sensor.oura_sleep_latency", "720", { unit_of_measurement: "s" }],
  ["sensor.oura_average_sleep_heart_rate", "54", { unit_of_measurement: "bpm" }],
  ["sensor.oura_average_sleep_hrv", "42", { unit_of_measurement: "ms" }],
  ["sensor.oura_current_heart_rate", "62", { unit_of_measurement: "bpm" }],
  ["sensor.oura_lowest_sleep_heart_rate", "51", { unit_of_measurement: "bpm" }],
  ["sensor.oura_steps", "6400"],
  ["sensor.oura_active_calories", "420", { unit_of_measurement: "kcal" }],
  ["sensor.oura_total_calories", "2360", { unit_of_measurement: "kcal" }],
  ["sensor.oura_target_calories", "500", { unit_of_measurement: "kcal" }],
  ["sensor.oura_low_activity_time", "18000", { unit_of_measurement: "s" }],
  ["sensor.oura_ring_battery_level", "68", { unit_of_measurement: "%" }],
  ["sensor.oura_bedtime_start", "2026-07-10T22:40:00+02:00"],
  ["sensor.oura_temperature_deviation", "0.2", { unit_of_measurement: "°C" }],
  ["sensor.oura_spo2_average", "96.4", { unit_of_measurement: "%" }],
  ["sensor.oura_last_workout_type", "walking"],
  ["sensor.oura_last_workout_intensity", "moderate"],
  ["sensor.oura_last_workout_duration", "27", { unit_of_measurement: "min" }],
  ["sensor.oura_last_workout_distance", "2204", { unit_of_measurement: "m" }],
  ["sensor.oura_last_workout_calories", "146", { unit_of_measurement: "kcal" }],
  // Vitality optimiser
  ["sensor.vitality_current_tier", "Bronze"],
  ["sensor.vitality_next_tier", "Silver"],
  ["sensor.vitality_points_to_next_tier", "12600", { unit_of_measurement: "pts" }],
  ["input_number.vitality_points_annual", "37400", { min: 0, max: 120000, step: 100 }],
  ["input_number.vitality_threshold_bronze", "15000"],
  ["input_number.vitality_threshold_silver", "50000"],
  ["input_number.vitality_threshold_gold", "80000"],
  ["input_number.vitality_threshold_diamond", "100000"],
  ["input_select.vitality_status", "Bronze", { options: ["Blue", "Bronze", "Silver", "Gold", "Diamond"] }],
  ["sensor.vitality_weekly_goal_progress", "33", { estimated: 300, goal: 900, remaining: 600 }],
  ["sensor.vitality_gym_discount_status", "22 visits to 75% off", { visits: 14, target: 36, on_track: false }],
  ["sensor.vitality_cardio_fitness_level", "Good", { vo2_max: 41 }],
  ["input_number.vitality_gym_visits_12mo", "14", { min: 0, max: 400, step: 1 }],
  // HQ money bridge
  ["input_number.hq_net_worth", "4285000"],
  ["input_number.hq_total_balance", "128400"],
  ["input_number.hq_available", "41250"],
  ["input_text.hq_updated", "2026-07-18 19:40"],
  ["input_boolean.hq_money_alerts", "on"],
  ["sensor.oura_workouts_today", "1"],
  ["sensor.oura_medium_activity_met_minutes", "127", { unit_of_measurement: "min" }],
  ["sensor.oura_high_activity_met_minutes", "0", { unit_of_measurement: "min" }],
  ["input_boolean.oura_readiness_actions_enabled", "on"],
  ["input_boolean.oura_activity_nudge_enabled", "on"],
  ["input_boolean.printer_ink_notifications", "on"],

  // Timeline — room PIRs, geocoded locations, kids phone
  ["binary_sensor.main_room_pir", "off"],
  ["binary_sensor.helloliam_alarm_zone_003_pir_kids_room", "off"],
  ["binary_sensor.helloliam_alarm_zone_007_pir_tv_room", "on"],
  ["binary_sensor.lounge_pir", "off"],
  ["binary_sensor.kitchen_pir", "off"],
  ["binary_sensor.garage_pir", "off"],
  ["binary_sensor.passage_pir", "off"],
  ["binary_sensor.guest_room_pir", "off"],
  ["sensor.hello_geocoded_location", "14 Wyoming Ave, Sandton"],
  ["sensor.kid_s_phone_geocoded_location", "Redhill School, Morningside"],
  ["sensor.kid_s_phone_battery_level", "72", { unit_of_measurement: "%" }],

  // Pump live power — borehole set high to demo "pumping"; water idling; pool off
  ["switch.borehole_pump", "on"],
  ["sensor.borehole_pump_power_now", "1123", { unit_of_measurement: "W" }],
  ["sensor.borehole_pump_actual_flow_rate", "34", { unit_of_measurement: "L/min" }],
  ["sensor.borehole_pump_run_time_today", "42 min"],
  ["sensor.borehole_pump_energy", "1.9", { unit_of_measurement: "kWh" }],
  ["sensor.borehole_pump_cost_today", "6.60", { unit_of_measurement: "R" }],
  ["sensor.borehole_pump_efficiency", "1820", { unit_of_measurement: "L/kWh" }],
  ["sensor.borehole_pump_cost_per_liter", "0.0021", { unit_of_measurement: "R/L" }],
  ["sensor.borehole_pump_avg_power", "1180", { unit_of_measurement: "W" }],
  ["sensor.borehole_pump_cost_this_month", "142.80", { unit_of_measurement: "R" }],
  ["sensor.water_pump_power", "3", { unit_of_measurement: "W" }],
  ["sensor.pool_pump_power_now", "0", { unit_of_measurement: "W" }],

  // Christo's iPhone
  ["sensor.hello_battery_level", "68", { unit_of_measurement: "%" }],
  ["sensor.hello_battery_state", "Not Charging"],
  ["sensor.hello_ssid", "Steyn-Home-5G"],
  ["sensor.hello_connection_type", "Wi-Fi"],
  ["sensor.hello_steps", "4820"],
  ["sensor.hello_distance", "3.4", { unit_of_measurement: "km" }],
  ["sensor.hello_floors_ascended", "6"],
  ["sensor.hello_activity", "Walking"],
  ["sensor.hello_storage", "42.1", { unit_of_measurement: "GB" }],

  // Kids' phone extras (Android)
  ["sensor.kid_s_phone_battery_state", "Charging"],
  ["sensor.kid_s_phone_battery_health", "Good"],
  ["sensor.kid_s_phone_remaining_charge_time", "38 min"],
  ["sensor.kid_s_phone_wi_fi_connection", "Redhill-Guest"],
  ["sensor.kid_s_phone_data_network_type_sim_1", "LTE"],
  ["sensor.kid_s_phone_steps_sensor", "6120"],
  ["sensor.kid_s_phone_detected_activity", "Still"],
  ["sensor.kid_s_phone_ringer_mode", "Vibrate"],
  ["sensor.kid_s_phone_last_used_app", "YouTube Kids"],
];

export const MOCK: HassEntities = Object.fromEntries(
  ROWS.map(([id, state, attrs], i) => {
    // stagger last_changed over the past few hours so the Overview logbook demos
    const ts = new Date(Date.now() - (i * 137_000 + 60_000)).toISOString();
    return [
      id,
      {
        entity_id: id,
        state,
        attributes: { friendly_name: id, ...(attrs ?? {}) },
        last_changed: ts,
        last_updated: ts,
        context: { id: "", user_id: null, parent_id: null },
      },
    ];
  }),
) as unknown as HassEntities;
